### PR TITLE
Validate bodylength and checksum

### PR DESCRIPTION
**Pull request by whatthefrog**
Hi, 

I have added an automated validation feature to your fix-decoder tool.
It checks both the BodyLength(9) and the Checksum(10) against the values given in the FIX messages, and colorise the fields in green if valid, or red if invalid, given the expected value at the same time.

image

I use your tool often, and got stuck one day doing testing, because I wasn't sending the correct length building some FIX messages by hand, not the best idea to start with agreed, but I thought it would be a nice addition to nice tool.

Best

Julien

### CODE REVIEW

**Comment by drewnoakes** [comment]
Fantastic stuff.

Would you like to be added as a collaborator on this repo?

**Comment by whatthefrog** [comment]
Afternoon, thanks for the merge. 
Adding me as a collaborator, why not ? not sure what that involves, being quite new to github specifically and open source contributions in general. So far I can only think of one thing: add a little navigation resume on the top left, to give an overview of the dialog ... but this is a bit of work.

**Comment by drewnoakes** [comment]
Great. You're a collaborator now which means you can now push freely to the repo. I trust your judgement completely.

**Comment by whatthefrog** [comment]
Thanks, that was a rewarding contribution then ;-)
I will keep proposal in feature branches but form your repo then, and submit pull requests the same way so we can discuss details, if needed, before merging to master then ...

**Comment by drewnoakes** [comment]
If you'd rather produce feature branches, that's fine. I'm happy with whatever works best for you.

**Pull request merged**
